{{- if or .Values.mysql.sockets ( or .Values.tomcat.Enabled .Values.tomcat.ini ) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{template "fineract.fullname" .}}-tomcat
  labels:
    app: {{ template "fineract.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  additional.ini: |
  {{- if .Values.tomcat.ini }}
{{ .Values.tomcat.ini  | indent 4 }}
  {{- end }}
  {{- if .Values.mysql.sockets }}
    mysqli.default_socket=/var/run/mysqld/mysqld.sock
    pdo_mysql.default_socket=/var/run/mysqld/mysqld.sock
  {{- end }}
  {{- if .Values.tomcat.fpmEnabled }}
  zz-docker.conf: |
    [global]
    daemonize = no
    [www]
    listen = /var/run/tomcat/tomcat.sock
    listen.mode = 0666
  {{- end }}
{{- end }}
