{{- if and .Values.ingress.enabled (or .Values.tomcatmyadmin.enabled .Values.webdav.enabled) }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fineract.fullname" . }}-service
  annotations:
    {{- if .Values.ingress.ssl }}
    kubernetes.io/tls-acme: "true"
    {{- end }}
{{ toYaml .Values.ingress.annotations | indent 4 }}
spec:
  {{- if .Values.ingress.ssl }}
  tls:
  - secretName: {{ template "fineract.fullname" . }}-tls-service
    hosts:
    {{- if .Values.tomcatmyadmin.enabled }}
    - {{ .Values.tomcatmyadmin.subdomain }}.{{ template "fineract.domain" . }}
    {{- end }}
    {{- if .Values.webdav.enabled }}
    - {{ .Values.webdav.subdomain }}.{{ template "fineract.domain" . }}
    {{- end }}
  {{- end }}
  rules:
  {{- if .Values.tomcatmyadmin.enabled }}
  - host: {{ .Values.tomcatmyadmin.subdomain }}.{{ template "fineract.domain" . }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "fineract.fullname" . }}
          servicePort: {{ .Values.tomcatmyadmin.port }}
  {{- end }}
  {{- if .Values.webdav.enabled }}
  - host: {{ .Values.webdav.subdomain }}.{{ template "fineract.domain" . }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "fineract.fullname" . }}
          servicePort: {{ .Values.webdav.port }}
  {{- end }}
{{- end }}
