apiVersion: v1
kind: Service
metadata:
  name: {{ template "fineract.fullname" . }}
  labels:
    app: {{ template "fineract.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  {{- if .Values.ingress.enabled }}
  type: ClusterIP
  {{- else }}
  type: {{ .Values.service.type }}
  {{- end }}
  ports:
  - port: {{ .Values.service.HTTPPort }}
    targetPort: 80
    protocol: TCP
    name: httpd
  {{ if .Values.mysql.rootPassword }}
  - port: 3306
    targetPort: 3306
    protocol: TCP
    name: mysql
  {{ end }}  
  {{ if .Values.phpmyadmin.enabled }}
  - port: {{ .Values.tomcatmyadmin.port }}
    targetPort: 8080
    protocol: TCP
    name: tomcatpmyadmin
  {{ end }}
  selector:
    app: {{ template "fineract.name" . }}
    release: {{ .Release.Name }}
